# A Simple Scikit-Learn Classification Workflow

This notebook shows a breif workflow you might use with `scikit-learn` to build a machine learning model to classify whether or not a patient has heart disease.

It follows the diagram below:

<img src="../images/sklearn-workflow.png"/>

**Note:** This workflow assumes your data is ready to be used with machine learning models (is numerical, has no missing values).

In [1]:
# Standard imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## 1. Get the data ready

In [2]:
# Import dataset
heart_disease = pd.read_csv("../data/heart_disease.csv")

# View the data
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

With this example, we're going to use all of the columns except the target column to predict the targert column.

In other words, using a patient's medical and demographic data to predict whether or not they have heart disease.

In [3]:
# Create X (all the feature columns)
X = heart_disease.drop("target", axis=1)

# Create y (the target column)
y = heart_disease["target"]

In [4]:
# Split the data into training and test sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

# View the data shapes
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((227, 13), (76, 13), (227,), (76,))

## 2. Choose the model/estimator

You can do this using the [Scikit-Learn machine learning map](https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html).

<img src="../images/sklearn-cheatsheet.png" width=800/>

In Scikit-Learn, machine learning models are referred to as estimators.

In this case, since we're working on a classification problem, we've chosen the RandomForestClassifier estimator which is part of the ensembles module.

In [5]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()

## 3. Fit the model to the data and use it to make a prediction

A model will (attempt to) learn the patterns in a dataset by calling the `fit()` function on it and passing it the data.

In [6]:
model.fit(X_train, y_train);

Once a model has learned patterns in data, you can use them to make a prediction with the `predict()` function.

In [7]:
# Make predictions
y_preds = model.predict(X_test)

In [8]:
# This will be in the same format as y_test
y_preds

array([1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1])

In [9]:
X_test.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
130   54    0   2       160   201    0        1      163      0      0.0   
54    63    0   2       135   252    0        0      172      0      0.0   
49    53    0   0       138   234    0        0      160      0      0.0   
107   45    0   0       138   236    0        0      152      1      0.2   
134   41    0   1       126   306    0        1      163      0      0.0   

     slope  ca  thal  
130      2   1     2  
54       2   0     2  
49       2   0     2  
107      1   0     2  
134      2   0     2

In [10]:
X_test.loc[107] # Change the index according to the index of X_test

age          45.0
sex           0.0
cp            0.0
trestbps    138.0
chol        236.0
fbs           0.0
restecg       0.0
thalach     152.0
exang         1.0
oldpeak       0.2
slope         1.0
ca            0.0
thal          2.0
Name: 107, dtype: float64

In [11]:
heart_disease.loc[107]

age          45.0
sex           0.0
cp            0.0
trestbps    138.0
chol        236.0
fbs           0.0
restecg       0.0
thalach     152.0
exang         1.0
oldpeak       0.2
slope         1.0
ca            0.0
thal          2.0
target        1.0
Name: 107, dtype: float64

In [14]:
# Make a prediction on a single sample (has to be array)
model.predict(np.array(X_test.loc[107]).reshape(1, -1))

e:\Machine-Learning-Data-Science\sklearn_env\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1])

## 4. Evaluate the model
A trained model/estimator can be evaluated by calling the `score()` function and passing it a collection of data.

In [15]:
# On the training set
model.score(X_train, y_train)

1.0

In [16]:
# On the test set (unseen)
model.score(X_test, y_test)

0.8552631578947368

## 5. Experiment to improve (hyperparameter tuning)

A model's first evaluation metrics aren't always its last. One way to improve a models predictions is with hyperparameter tuning.

In [17]:
# Try different numbers of estimators (n_estimators is a hyperparameter you can change)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators...")
    model = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accruacy on test set: {model.score(X_test, y_test)}\n")

Trying model with 10 estimators...
Model accruacy on test set: 0.8026315789473685

Trying model with 20 estimators...
Model accruacy on test set: 0.8026315789473685

Trying model with 30 estimators...
Model accruacy on test set: 0.8157894736842105

Trying model with 40 estimators...
Model accruacy on test set: 0.881578947368421

Trying model with 50 estimators...
Model accruacy on test set: 0.8026315789473685

Trying model with 60 estimators...
Model accruacy on test set: 0.8552631578947368

Trying model with 70 estimators...
Model accruacy on test set: 0.868421052631579

Trying model with 80 estimators...
Model accruacy on test set: 0.8421052631578947

Trying model with 90 estimators...
Model accruacy on test set: 0.7894736842105263



**Note:** It's best practice to test different hyperparameters with a validation set or cross-validation.

In [18]:
from sklearn.model_selection import cross_val_score

# Try different numbers of estimators with cross-validation and no cross-validation
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators...")
    model = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accruacy on test set: {model.score(X_test, y_test)}")
    print(f"Cross-validation score: {np.mean(cross_val_score(model, X, y, cv=5))*100}%\n")

Trying model with 10 estimators...
Model accruacy on test set: 0.7894736842105263
Cross-validation score: 78.8415300546448%

Trying model with 20 estimators...
Model accruacy on test set: 0.8421052631578947
Cross-validation score: 82.16939890710384%

Trying model with 30 estimators...
Model accruacy on test set: 0.8289473684210527
Cross-validation score: 81.1639344262295%

Trying model with 40 estimators...
Model accruacy on test set: 0.8157894736842105
Cross-validation score: 84.47540983606558%

Trying model with 50 estimators...
Model accruacy on test set: 0.8026315789473685
Cross-validation score: 81.49726775956283%

Trying model with 60 estimators...
Model accruacy on test set: 0.8157894736842105
Cross-validation score: 82.49180327868851%

Trying model with 70 estimators...
Model accruacy on test set: 0.8157894736842105
Cross-validation score: 81.18579234972675%

Trying model with 80 estimators...
Model accruacy on test set: 0.8157894736842105
Cross-validation score: 80.50819672131

## 6. Save a model for later use

A trained model can be exported and saved so it can be imported and used later. One way to save a model is using Python's `pickle` module.

In [19]:
import pickle

# Save trained model to file
pickle.dump(model, open("random_forest_model.pkl", "wb"))

In [21]:
# Load a saved model and make a prediction on a single example
loaded_model = pickle.load(open("random_forest_model.pkl", "rb"))
loaded_model.predict(np.array(X_test.loc[107]).reshape(1, -1))

e:\Machine-Learning-Data-Science\sklearn_env\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1])